apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
data:
  script.js: |
    import { check, sleep } from 'k6';
    import kafka from 'k6/x/kafka';
    import { b64encode } from 'k6/encoding'; // 1. 인코딩 모듈 import

    const writer = new kafka.Writer({
        brokers: ['kafka.default.svc.cluster.local:9092'],
        topic: 'edip.events',
    });

    export const options = {
        stages: [
            { duration: '20s', target: 100 },
            { duration: '20s', target: 100 },
            { duration: '20s', target: 0 },
        ],
    };

    export default function () {
        writer.produce({
            messages: [
                // 2. key와 value를 Base64로 인코딩
                { 
                  key: b64encode(`key-${__VU}-${__ITER}`), 
                  value: b64encode(`value-${__VU}-${__ITER}`) 
                },
            ]
        });
        sleep(1);
    }

    export function teardown(data) {
        writer.close();
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-kafka-test
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: k6
        image: mostafamoradian/xk6-kafka:latest
        command: ["k6", "run", "/scripts/script.js"]
        volumeMounts:
        - name: k6-script-volume
          mountPath: /scripts
      volumes:
      - name: k6-script-volume
        configMap:
          name: k6-script
      restartPolicy: Never
  backoffLimit: 4
